package src {
    // stages are used to increment player progression, so that the players may rehash the same content w/ a different color and increased variables,
    // it allows to maximize the idle.
    public class Level_Stage {
                                               
        public static const Stage_Color:Array = [
                                                "Stock",
                                                "Red",
                                                "Blue",
                                                "Brown",
                                                "Purple",
                                                "Green",
                                                "Orange",
                                                "Pink",
                                                "White",
                                                "Black", // 10
                                                "Shiny",
                                                "Transparent",
                                                "Upside Down",
                                                "Ultimate", // ultimate is where transparent and shiny are applied
                                                "Ultimate Finale", // Stock only
                                                "Shiny Red",
                                                "Shiny Blue",
                                                "Shiny Brown",
                                                "Shiny Purple",
                                                "Shiny Green", // 20
                                                "Shiny Orange",
                                                "Shiny Pink",
                                                "Shiny White",
                                                "Shiny Black",
                                                "Shiny Shiny",
                                                "Transparent Red",
                                                "Transparent Blue",
                                                "Transparent Brown",
                                                "Transparent Purple",
                                                "Transparent Green", // 30
                                                "Transparent Orange",
                                                "Transparent Pink",
                                                "Transparent White",
                                                "Transparent Black",
                                                "Transparent Shiny",
                                                "Transparent Transparent",
                                                "Upside Down Red",
                                                "Upside Down Blue",
                                                "Upside Down Brown",
                                                "Upside Down Purple", // 40
                                                "Upside Down Green",
                                                "Upside Down Orange",
                                                "Upside Down Pink",
                                                "Upside Down White",
                                                "Upside Down Black",
                                                "Upside Down Shiny",
                                                "Upside Down Transparent",
                                                "Upside Down Upside Down",
                                                "Ultimate Red",
                                                "Ultimate Blue", // 50
                                                "Ultimate Brown",
                                                "Ultimate Purple",
                                                "Ultimate Green",
                                                "Ultimate Orange",
                                                "Ultimate Pink",
                                                "Ultimate White",
                                                "Ultimate Black",
                                                "Ultimate Shiny",
                                                "Ultimate Transparent",
                                                "Ultimate Shiny Transparent", // 60
                                                "Ultimate Upside Down",
                                                "Ultimate Shiny Upside Down",
                                                "Ultimate Shiny Transparent Upside Down",
                                                "Ultimate Finale Finale" // everything is normal (64)
                                                ],
                            Stage_Player_Mult:Array = [// x = static_cast<float>(static_cast<int>((x*1.2f)*10.f))/10.f;
                                1,
                                1.5,
                                2.2,
                                3.3,
                                4.9,
                                7.3,
                                10.9,
                                16.3,
                                24.4,
                                36.5,
                                54.7,
                                82,
                                123,
                                184.5,
                                276.7,
                                415,
                                622.5,
                                933.7,
                                1400.5,
                                2100.7,
                                3151,
                                4726.5,
                                7089.7,
                                10634.5,
                                15951.7,
                                23927.5,
                                35891.2,
                                53836.8,
                                80755.2,
                                121132.8,
                                181699.2,
                                272548.8,
                                408823.1,
                                613234.6,
                                919851.9,
                                1379777.8,
                                2069666.7,
                                3104500,
                                4656750,
                                6985125,
                                10477687.5,
                                15716531.2,
                                23574796.7,
                                35362195,
                                53043292.5,
                                79564938.7,
                                119347408,
                                179021112,
                                268531668,
                                402797502,
                                604196253,
                                906294379.5,
                                1359441569.2,
                                2039162353.8,
                                3058743530.7,
                                4588115296,
                                6882172944,
                                10323259416,
                                15484889124,
                                23227333686,
                                34841000529,
                                52261500793.5,
                                78392251190.2
                                                      ],
                            Stage_Enemy_Mult:Array = [ // x = static_cast<float>(static_cast<int>(std::ceil((x*1.2f)*10.f)))/10.f;
                                1,
                                1.7,
                                2.8,
                                4.7,
                                7.9,
                                13.4,
                                22.7,
                                38.5,
                                65.4,
                                111.1,
                                188.8,
                                320.9,
                                545.5,
                                927.3,
                                1576.4,
                                2679.8,
                                4555.6,
                                7744.5,
                                13165.6,
                                22381.5,
                                38048.5,
                                64682.4,
                                109960,
                                186932,
                                317784.3,
                                540233.3,
                                918396.6,
                                1561274.2,
                                2654166.1,
                                4512082.3,
                                7670539.9,
                                13039917.8,
                                22167860.2,
                                37685362.3,
                                64065115.9,
                                108910697,
                                185148184.9,
                                314751914.3,
                                535078254.3,
                                909633032.3,
                                1546376154.9,
                                2628839463.3,
                                4469027087.6,
                                7597346048.9,
                                12915488283.1,
                                21956330081.2,
                                37325761138,
                                63453793934.6,
                                107871449688.8,
                                183381464470.9,
                                311748489600.5,
                                529972432320.8,
                                900953134945.3,
                                1531620329407,
                                2603754559991.9,
                                4426382751986.2,
                                7524850678376.5,
                                12792246153240,
                                21746818460508,
                                36969591382863.6,
                                62848305350868.1,
                                106842119096476,
                                181631602464009
                                                     ];
    }

}